FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# cae

Polls is a simple API allowing consumers to view polls and vote in them.

## Games Collection [/questions]

### List All Games [GET]

List all games you are allowed to see

+ Response 200 (application/json)
    + Attributes (array[Game])

### Create a New Game [POST]

Description goes here.

+ Request (application/json)
    + Attributes (Game Create)

+ Response 201 (application/json)

    + Headers

            Location: /games/2

    + Attributes (Game)
            
# Data Structures

## User (object)
+ id: 12 (number)
+ name: Mark (string) non-unique username

## Game Create (object)
+ name: `Cloe's Game` (string, required) - non-unique game name
+ password: `supersecret` (string) - optional game password, automatically makes it private

## Game (object)
+ id: 2 (number)
+ name: `Cloe's Game` (string) - non-unique game name
+ players (array[User])